import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import DotPattern from "@/components/magicui/dot-pattern";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "JENZY",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-foreground font-sans antialiased relative",
          fontSans.variable
        )}
      >
        <aside>
          <DotPattern
            className={cn(
              "-z-10 [mask-image:radial-gradient(500px_circle_at_top_left,white,transparent)]"
            )}
          />
          <DotPattern
            className={cn(
              "-z-10 [mask-image:radial-gradient(500px_circle_at_bottom_right,white,transparent)]"
            )}
          />
        </aside>
        <main className="z-10 text-white relative">{children}</main>
      </body>
    </html>
  );
}
